### ISSUE TITLE
Remove waiting?

### ISSUE THREAD

**Issue by ecnivo** [Bimde/Blackjack-Server#37]
Make a version for <b>AIs</b> that remove sleeps, so that I don't have to wait twenty minutes for a single game to complete?

**Comment by xuwilliam01** [comment]
Yeah we can just remove all the sleeps and publish that as a separate file.
Though it may be buggy idk

**Comment by Bimde** [comment]
We might slightly reduce the delay time if all other clients approve it. However we will not be adding any new features from today onward due to the possibility of creating more bugs. You can create this yourself for your testing using the 'DELAY' constant in the Server class, which could be changed to your heart's content.

**Comment by ecnivo** [comment]
Thank you.

**Comment by ecnivo** [comment]
Can you also put a flag on the sysouts? It slows down things when testing. Thanks!

Also when setting DELAY to 0, there's still pausing somewhere or another...
