### ISSUE TITLE
Randomize more often 

### ISSUE THREAD

**Issue by ecnivo** [Bimde/Blackjack-Server#39]
Randomize the ArrayList each time you deal. Because @Netdex

**Comment by Bimde** [comment]
Better reasons?

**Comment by Bimde** [comment]
I think I know what you mean, to prevent players from trying to join last in order to have more cards for card counting? If so, this makes sense. However, this may mess up clients who are using the increasing order of the player numbers for whatever reason (even though I think this is not a smart implementation). This will be looked into tomorrow if it could be implemented without affecting the doc / anyone else.

**Comment by ecnivo** [comment]
It could be preventing certain clients from getting the seed you use for randomizing during Collections.shuffle()

**Comment by Bimde** [comment]
Created new issue without misinterpretation.
